AWSTemplateFormatVersion: "2010-09-09"

Description: |
  joniAssessmentTest2Uusinta

Resources: 
  joniDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
        
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
        